### ISSUE TITLE
"https" is not used as the default

### ISSUE THREAD

**Issue by tobias47n9e** [m2mtech/weblate-translation-provider#3]
When pushing translations, I run into this odd bug with a self-hosted Weblate instance. I spent some time debugging it myself and then also asked the question here: https://stackoverflow.com/questions/73389431/symfony-weblate-eror-when-pushing-component-translations

The documentation suggests that the default configuration uses `https` to connect to Weblate, which can be set to `false` (Source: https://github.com/m2mtech/weblate-translation-provider/blob/main/README.md?plain=1#L46).

But when looking at the requests that are made during pushing, some of them are made using `http` and get redirected by Weblate (or a proxy?) with status code 308. The redirect also drops the trailing slash at the end (e.g. `messages/translations/` -> `messages/translations`).

It's probably something that could also be fixed on the proxy- or Weblate-side, but it would be nice if the package could handle this too. I made a rather crude patch, which I will submit, but there is probably a better solution.

**Comment by m2mtech** [comment]
Please note that the mention of the default `https` refers to the creation of `URLs` from the configuration used when setting up the provider:

https://github.com/m2mtech/weblate-translation-provider/blob/3af95203448161f774a4d48cf0c835c779c6466c/src/WeblateProviderFactory.php#L74-L77

and then when they need to be generated by the API:

https://github.com/m2mtech/weblate-translation-provider/blob/3af95203448161f774a4d48cf0c835c779c6466c/src/Api/ComponentApi.php#L71

Later, the API tries to only use links provided directly by weblate. E.g. the one from your [SO question](https://stackoverflow.com/questions/73389431/symfony-weblate-eror-when-pushing-component-translations) is taken from the above request and then used here:

https://github.com/m2mtech/weblate-translation-provider/blob/3af95203448161f774a4d48cf0c835c779c6466c/src/Api/TranslationApi.php#L62

It seems that your weblate instance is unaware that it is behind an HTTPS proxy and is therefore generating invalid URLs that are "fixed" by your proxy.

Please check if you have set [`ENABLE_HTTPS`](https://docs.weblate.org/en/latest/admin/config.html#enable-https), `HTTP_X_FORWARDED_FOR` et al. correctly.

> It's probably something that could also be fixed on the proxy- or Weblate-side, but it would be nice if the package could handle this too. I made a rather crude patch, which I will submit, but there is probably a better solution.

I would prefer if a problem is tackled at its source.

**Comment by tobias47n9e** [comment]
Thanks for the analysis. I was already suspicious that it was an issue with the config of the Kubernetes&Helm Weblate-template on Rancher. I will check the ingress settings and report back as soon as I know what fixes this issue, although as you say it is not caused by this library.

**Comment by tobias47n9e** [comment]
I can now confirm that the issue was caused by the missing https://docs.weblate.org/en/latest/admin/config.html#enable-https option. Thanks for the help!
